### PR TITLE
add styling to Bookstore App

### PR DESCRIPTION
**Pull request by demix007**
## In this milestone of my Bookstore App, I implemented the following:

- Styled the app according to the Bookstore design in [Zeplin](https://zeplin.io/) provided in the project requirements.
- Added missing JSX elements to the project.
- Used the CSS rules detailed in Bookstore Zeplin to style the website.
- Ensured that the final design matched the Bookstore Zeplin design.
- Made sure there were [no linter errors](https://github.com/microverseinc/linters-config).
- Used the correct flow [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Documented my work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

### CODE REVIEW

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi @demix007, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 

## Highlights 💪 
- No linter errors
- correct flow is used
- good PR
-  design look great 💯 

## Required Changes ♻️

- [ ] Good job so far 👏 👏 your project looks good! In addition to what you have done, I would suggest that you use the UPDATED [README TEMPLATE](https://github.com/microverseinc/readme-template) as provided by Microverse. Remember to cover each section in the template 😃 👍 This will make your README look more professional

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by demix007** [comment]
Hello @BertrandConxy  👋🏼 ,

Thank you for taking out time to review this request. The required changes which you suggested have been swiftly implemented. 💯

**Review by tugsem — APPROVED** [review]
## STATUS: APPROVED 👍🎯  
Hi @demix007 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⭐ 
✔️ You have implemented the requested changes

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by demix007** [comment]
## Hello @tugsem 👋🏼 ,

Thank you for taking out time to review and approve this PR. You are amazing 💯

**Comment by BertrandConxy** [comment]
Great 👌 please go ahead and request another review

**Pull request merged**
