### PR TITLE
initialize project with components

### PR DESCRIPTION
**Pull request by demix007**
## In this milestone of my Bookstore App, I implemented the following changes:

- Initialised React app.
-  Created a directory for the components and set the building blocks of the app as re-usable components.
- Added [React Router](https://reactrouter.com/web/guides/quick-start) and set two Routes and Links for the app's navigation:
  💠 Books: the default view.
  💠 Categories: displays a button "Check status" only.
- Used React Router to make routes work. 
- Made sure that there were no linter errors
- Used the correct Gitflow
- Documented the project in a professional way. 
- Followed Javascript best practices.

### CODE REVIEW

**Review by cynthiainga — COMMENTED** [review]
Hi @demix007, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't use a given `README` template by microverse. Please kindly update your `README` file by using this [template](https://github.com/microverseinc/readme-template#readme-top) 😉 😉

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by demix007** [comment]
## Hello @cynthiainga 👋🏼,
 Thank you for taking out time to review this PR. I have made the required changes to the README.md file just as you have suggested. Thank you for the insightful feedback.

**Review by m05e5 — APPROVED** [review]
Hi @demix007 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
goodjob

## Highlights
✔️ your linters are all ok
✔️ Descriptive PR 

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by demix007** [comment]
## Hello @m05e5 👋🏼,
 
Thank you for reviewing and approving this PR. You are awesome! 💯

**Pull request merged**
